// array för 15 fake polaroider
let adminPolaroidArray = [
    {
        pic: '../images/static/travel_1.jpg',
        avatar: '../images/static/person_1.jpg',
        avatarName: 'mandy1',
        coutry: 'Turkey',
        title: 'Air baloons in Cappadocia',
    },
    {
        pic: '../images/static/travel_2.jpg',
        avatar: '../images/static/person_2.jpg',
        avatarName: 'travelCharlie',
        coutry: 'Spain',
        title: 'My hike on La Gomera',
    },
    {
        pic: '../images/static/travel_3.jpg',
        avatar: '../images/static/person_3.jpg',
        avatarName: 'backpacker_maher',
        coutry: 'Indonesia',
        title: 'Stunning sunsets on Bali',
    },
    {
        pic: '../images/static/travel_4.jpg',
        avatar: '../images/static/person_3.jpg',
        avatarName: 'backpacker_maher',
        coutry: 'USA',
        title: 'Coast to Coast with Doggo',
    },
    {
        pic: '../images/static/travel_5.jpg',
        avatar: '../images/static/person_1.jpg',
        avatarName: 'mandy1',
        coutry: 'Greece',
        title: 'Island hoping with my best friend',
    },
    {
        pic: '../images/static/travel_6.jpg',
        avatar: '../images/static/person_2.jpg',
        avatarName: 'travelCharlie',
        coutry: 'Filipines',
        title: 'We found heaven',
    },
    {
        pic: '../images/static/travel_7.jpg',
        avatar: '../images/static/person_3.jpg',
        avatarName: 'backpacker_maher',
        coutry: 'Thailand',
        title: 'My favourite hotels in Thailand',
    },
    {
        pic: '../images/static/travel_8.jpg',
        avatar: '../images/static/person_1.jpg',
        avatarName: 'mandy1',
        coutry: 'Scotland',
        title: 'We reached The Old man if Storr',
    },
    {
        pic: '../images/static/travel_9.jpg',
        avatar: '../images/static/person_2.jpg',
        avatarName: 'travelCharlie',
        coutry: 'Austria',
        title: 'Four months in the Alps',
    },
    {
        pic: '../images/static/travel_10.jpg',
        avatar: '../images/static/person_2.jpg',
        avatarName: 'travelCharlie',
        coutry: 'Italy',
        title: 'Venice in August',
    },
    {
        pic: '../images/static/travel_11.jpg',
        avatar: '../images/static/person_3.jpg',
        avatarName: 'backpacker_maher',
        coutry: 'Turkey',
        title: 'Roadtrip around Turkey',
    },
    {
        pic: '../images/static/travel_12.jpg',
        avatar: '../images/static/person_1.jpg',
        avatarName: 'mandy1',
        coutry: 'Greece',
        title: 'A week at the sea',
    },
    {
        pic: '../images/static/travel_13.jpg',
        avatar: '../images/static/person_1.jpg',
        avatarName: 'mandy1',
        coutry: 'Jordan',
        title: 'Magical Wadi Rum',
    },
    {
        pic: '../images/static/travel_14.jpg',
        avatar: '../images/static/person_2.jpg',
        avatarName: 'travelCharlie',
        coutry: 'Australia',
        title: 'One year abroad',
    },
    {
        pic: '../images/static/travel_15.jpg',
        avatar: '../images/static/person_3.jpg',
        avatarName: 'backpacker_maher',
        coutry: '?',
        title: 'My favourite ancient places',
    },

]
